### PR TITLE
完善结构归类 兼容5.x内核

### PR DESCRIPTION
**Pull request by qiuzi**

### CODE REVIEW

**Comment by springsunx** [comment]
x86_64,5.4,修改后依然无法编译通过。

**Comment by qiuzi** [comment]
@springsunx 需要清空.config tmp 文件 因为这个依然内核编译顺序

**Comment by springsunx** [comment]
make[4]: Entering directory '/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.28'
  CC [M]  /home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.o
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c: In function '__add_app_feature':
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c:110:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
   char *p = dict;
   ^~~~
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c: In function 'add_app_feature':
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c:158:2: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  char *p = feature;
  ^~~~
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c:202:2: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  int dst_port = 0;
  ^~~
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c: In function 'af_init_feature':
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c:232:2: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  char *p = feature_str;
  ^~~~
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c:247:2: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  char feature[MAX_FEATURE_STR_LEN];;
  ^~~~
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c:248:2: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  int i;
  ^~~
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c:251:2: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  char *begin = feature_buf;
  ^~~~
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c:248:6: warning: unused variable 'i' [-Wunused-variable]
  int i;
      ^
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c: In function 'load_feature_buf_from_file':
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c:279:10: warning: 'return' with a value, in function returning void
   return -1;
          ^
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c:269:6: note: declared here
 void load_feature_buf_from_file(char **config_buf)
      ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c:24:
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c:284:10: warning: format '%d' expects argument of type 'int', but argument 2 has type 'off_t' {aka 'long int'} [-Wformat=]
  AF_INFO("feature file size: %d\n", size);
          ^~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/af_log.h:7:16: note: in definition of macro 'LOG'
         printk(fmt, ##__VA_ARGS__); \
                ^~~
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c:284:2: note: in expansion of macro 'AF_INFO'
  AF_INFO("feature file size: %d\n", size);
  ^~~~~~~
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c:286:11: warning: format '%d' expects argument of type 'int', but argument 2 has type 'off_t' {aka 'long int'} [-Wformat=]
   AF_WARN("warning, file size = %d\n", size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/af_log.h:7:16: note: in definition of macro 'LOG'
         printk(fmt, ##__VA_ARGS__); \
                ^~~
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c:286:3: note: in expansion of macro 'AF_WARN'
   AF_WARN("warning, file size = %d\n", size);
   ^~~~~~~
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c:293:10: warning: 'return' with a value, in function returning void
   return -1;
          ^
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c:269:6: note: declared here
 void load_feature_buf_from_file(char **config_buf)
      ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c:305:9: warning: 'return' with a value, in function returning void
  return size;
         ^~~~
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c:269:6: note: declared here
 void load_feature_buf_from_file(char **config_buf)
      ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c: In function 'load_feature_config':
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c:311:2: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  char *feature_buf = NULL;
  ^~~~
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c:318:2: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  char *p;
  ^~~~
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c:321:2: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  char line[MAX_FEATURE_LINE_LEN] = {0};
  ^~~~
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c: In function 'af_clean_feature_list':
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c:348:21: warning: unused variable 'n' [-Wunused-variable]
  af_feature_node_t *n,*node;
                     ^
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c: In function 'parse_http_proto':
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c:469:2: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  int i = 0;
  ^~~
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c: In function 'af_get_timestamp_sec':
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c:713:7: error: implicit declaration of function 'current_kernel_time'; did you mean 'current_time'? [-Werror=implicit-function-declaration]
  ts = current_kernel_time();
       ^~~~~~~~~~~~~~~~~~~
       current_time
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c:713:5: error: incompatible types when assigning to type 'struct timespec' from type 'int'
  ts = current_kernel_time();
     ^
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c: In function '__af_update_client_app_info':
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c:728:2: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  int found = 0;
  ^~~
In file included from /home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c:24:
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c:768:11: warning: format '%u' expects argument of type 'unsigned int', but argument 2 has type 'long unsigned int' [-Wformat=]
  AF_DEBUG("update time = %u\n", node->visit_info[index].latest_time);
           ^~~~~~~~~~~~~~~~~~~~  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/af_log.h:7:16: note: in definition of macro 'LOG'
         printk(fmt, ##__VA_ARGS__); \
                ^~~
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c:768:2: note: in expansion of macro 'AF_DEBUG'
  AF_DEBUG("update time = %u\n", node->visit_info[index].latest_time);
  ^~~~~~~~
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c:770:10: warning: format '%d' expects argument of type 'int', but argument 5 has type 'long unsigned int' [-Wformat=]
  AF_INFO("[%d] %pI4 visit %d, time=%d action=%s, %d/%d\n", index, &node->ip, flow->app_id,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   node->visit_info[index].latest_time, node->visit_info[index].latest_action ? "Drop" : "Accept",
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/af_log.h:7:16: note: in definition of macro 'LOG'
         printk(fmt, ##__VA_ARGS__); \
                ^~~
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c:770:2: note: in expansion of macro 'AF_INFO'
  AF_INFO("[%d] %pI4 visit %d, time=%d action=%s, %d/%d\n", index, &node->ip, flow->app_id,
  ^~~~~~~
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c: In function 'af_update_client_app_info':
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c:780:6: warning: unused variable 'index' [-Wunused-variable]
  int index = 0;
      ^~~~~
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c:779:6: warning: unused variable 'i' [-Wunused-variable]
  int i;
      ^
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c: In function 'app_filter_hook':
/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.c:833:2: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
  struct nf_conn_acct *acct;
  ^~~~~~
cc1: some warnings being treated as errors
make[5]: *** [scripts/Makefile.build:266: /home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/app_filter.o] Error 1
make[4]: *** [Makefile:1692: /home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0] Error 2
make[4]: Leaving directory '/home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/linux-5.4.28'
make[3]: *** [Makefile:44: /home/sunx/n1/build_dir/target-x86_64_musl/linux-x86_64/oaf-3.0/.built] Error 2
make[3]: Leaving directory '/home/sunx/lede/my_packages/oaf'
time: package/my_packages/oaf/compile#0.50#0.95#1.60
make[2]: *** [package/Makefile:113: package/my_packages/oaf/compile] Error 2
make[2]: Leaving directory '/home/sunx/n1'
make[1]: *** [package/Makefile:107: /home/sunx/n1/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/sunx/n1'
make: *** [/home/sunx/n1/include/toplevel.mk:227: world] Error 2

已删除tmp，并重新生成.config

**Comment by qiuzi** [comment]
这就麻烦了 看来得等5.4内核稳定后再看看吧

**Pull request closed without merging**
